source "http://rubygems.org"

gem "rails", "3.0.0"
gem "capybara", ">= 0.3.9"
gem 'mysql'

gem "overlord", :path => '../../'
gem "httparty"

if RUBY_VERSION < '1.9'
  gem "ruby-debug"
end

group :test do
  gem 'shoulda'
  gem 'factory_girl'
  gem 'mocha'
  gem 'redgreen'
  gem 'cucumber'
  gem 'webrat'
  gem 'rspec'
  gem 'rspec-rails'
end